package com.qed.course.stu.model;

import com.jfinal.plugin.activerecord.Db;
import com.qed.course.stu.model.base.BaseStu;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stu extends BaseStu<Stu> {
	public static final Stu dao = new Stu();

	Logger logger = LoggerFactory.getLogger(this.getClass().getName());


	public List<Stu> getStuList() {
		return find("SELECT * FROM stu");
	}

	public boolean unIsExisted(String un) {
		long count = Db.queryFirst("SELECT COUNT(*) FROM stu s WHERE s.un = ?", un);
		logger.debug("--count->>" + count);
		if (count > 0) {
			return true;
		}
		return false;
	}

}
